-- return {
--     {
--         'vimwiki/vimwiki',
--         init = function()
--             vim.g.vimwiki_list = { path = '~/notes', path_html = '~/notes/vimwiki-html', syntax = 'markdown', ext = '.md' }
--         end,
--     }
-- }
